import Header from "@/components/Header";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Link href="/about">About</Link>
        <Link href="/products">Products</Link>
        <Link href="/docs">Docs</Link>
        {children}
      </body>
    </html>
  );
}
